DROP TABLE IF EXISTS PRODUCT,MERCHANT,SUBCATEGORIES,CATEGORIES;

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    CATID
    SERIAL
    PRIMARY
    KEY,
    CATEGORYTYPE
    VARCHAR
(
    200
) NOT NULL,
    ADDINGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS SUBCATEGORIES
(
    CATID INTEGER REFERENCES CATEGORIES
(
    CATID
),
    SUBCATID SERIAL PRIMARY KEY,
    CATEGORYNAME VARCHAR
(
    200
) NOT NULL,
    ADDINGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS MERCHANT
(
    MID
    SERIAL
    PRIMARY
    KEY,
    NAME
    VARCHAR
(
    200
) NOT NULL,
    USERNAME VARCHAR
(
    200
) NOT NULL UNIQUE,
    PASSWORD VARCHAR
(
    200
) NOT NULL,
    ADDRESS TEXT DEFAULT NULL,
    PHONE INTEGER DEFAULT NULL,
    EMAIL VARCHAR
(
    200
) NOT NULL UNIQUE,
    GSTNUM VARCHAR
(
    200
) NOT NULL
    );

CREATE TABLE IF NOT EXISTS PRODUCT
(
    PID
    SERIAL
    PRIMARY
    KEY,
    SUBCATID
    INTEGER
    REFERENCES
    SUBCATEGORIES
(
    SUBCATID
),
    MID INTEGER REFERENCES MERCHANT
(
    MID
),
    PRICE NUMERIC NOT NULL,
    QUANTITY INTEGER NOT NULL,
    ADDINGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

INSERT INTO CATEGORIES(CATEGORYTYPE)
VALUES ('Electronics');

INSERT INTO SUBCATEGORIES(CATID, CATEGORYNAME)
VALUES (1,
        'Mobile'),
       (1,
        'Laptop');

INSERT INTO MERCHANT(NAME, USERNAME, PASSWORD, ADDRESS, PHONE, EMAIL, GSTNUM)
VALUES ('newMerchant',
        'newMerchant8740',
        'nm8740',
        'add',
        1234567890,
        'email',
        'gstnum');

INSERT INTO PRODUCT(SUBCATID, MID, PRICE, QUANTITY)
VALUES (1,
        1,
        900,
        20);